name: "CI"

concurrency:
  group: ${{ github.workflow }}-${{
           github.ref_name == 'main' && format('ci-main-build-test-{0}', github.run_id) ||
           format('ci-pr-build-test-on-{0}-against-branch-{1}', github.event_name, github.ref_name)
         }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "main"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        host-platform:
          - linux-64
          - linux-aarch64
          #- win-64
    name: Build ${{ matrix.host-platform }}
    if: ${{ github.repository_owner == 'nvidia' }}
    secrets: inherit
    uses:
      ./.github/workflows/build.yml
    with:
      host-platform: ${{ matrix.host-platform }}
      cuda-version: "12.8.0"

  test-linux:
    strategy:
      fail-fast: false
      # TODO: add driver version here
      matrix:
        host-platform:
          - linux-64
          - linux-aarch64
    name: Test ${{ matrix.host-platform }}
    if: ${{ github.repository_owner == 'nvidia' }}
    permissions:
      contents: read  # This is required for actions/checkout
    needs:
      - build
    secrets: inherit
    uses:
      ./.github/workflows/test-wheel-linux.yml
    with:
      build-type: pull-request
      host-platform: ${{ matrix.host-platform }}
      local-ctk: 1
      build-ctk-ver: 12.8.0
